version: '3'

services:
  app:
    image: ghcr.io/giglocal/website-devcontainer

    volumes:
      - ..:/workspace:cached
      - ${HOME}/.aspnet/https:/home/vscode/.aspnet/https:cached
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: Inter-Steller!08
      ACCEPT_EULA: Y
